name: Build projects

on: [push]

jobs:
  build:
    env:
      VERSION: grep -oP "version '([0-9]+\.[0-9]+\.[0-9]+)" build.gradle | cut -c 10-
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build root projects
      run: |
        chmod +x gradlew 
        ./gradlew shadowJar publishToMavenLocal --warning-mode all
    - name: Build forge-1_14_4
      run: |
        cd forge-1_14_4
        chmod +x gradlew 
        ./gradlew jar --warning-mode all
        cd ..
    - name: Archive Bukkit plugin
      uses: actions/upload-artifact@v1
      with:
        name: Iodine-bukkit-$VERSION.jar
        path: bukkit/build/libs/Iodine-bukkit-${{ env.VERSION }}.jar
    - name: Archive Forge mod
      uses: actions/upload-artifact@v1
      with:
        name: Iodine-bukkit-$VERSION.jar
        path: forge-1_14_4/build/libs/Iodine-forge-1_14_4-${{ env.VERSION }}.jar
